name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        # Action to check out the code so the workflow can access the Dockerfile and source files
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # Action to authenticate with Docker Hub using provided secrets
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        # Action to set up Docker Buildx, which provides powerful build capabilities
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags and labels) for Docker
        # Action to generate tags based on the Git ref (e.g., latest, or short commit SHA)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tedleyem/nagios

      - name: Build and push Docker image
        # Action to build the image and push it to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max