name: Initial Docker Deployment

on:
  workflow_dispatch:
    inputs:
      target_host:
        description: 'Nagios Server Hostname'
        required: true
        default: '8.8.4.4'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: pip install ansible

      - name: Create Ansible Inventory
        run: |
          echo "[servers]" > inventory
          echo "${{ github.event.inputs.target_host }} ansible_user=${{ secrets.ANSIBLE_USER }}" >> inventory

      - name: Run Docker Installation and Deployment Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./
          inventory: inventory
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --extra-vars "repo_path=${{ github.workspace }}"